[package]
name = "func-parser"
version = "0.1.0"
build = "build.rs"
description = "FunC Parser"
edition = "2021"

[build-dependencies]
lalrpop = "0.19"

[dependencies]
itertools = "0.10"
lalrpop-util = "0.19"
phf = { version = "0.11", features = ["macros"] }
regex = "1"
